//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSU.University.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationPlan
    {
        public int Id { get; set; }
        public int IdSpecialty { get; set; }
        public int IdDiscipline { get; set; }
        public int TotalTime { get; set; }
        public System.DateTime DateInstall { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Specialty Specialty { get; set; }
    }
}
