//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSU.University.MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UniversityEntities : DbContext
    {
        public UniversityEntities()
            : base("name=UniversityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Deducted> Deducted { get; set; }
        public virtual DbSet<Departament> Departament { get; set; }
        public virtual DbSet<Discipline> Discipline { get; set; }
        public virtual DbSet<EducationPlan> EducationPlan { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Faculty> Faculty { get; set; }
        public virtual DbSet<Graduates> Graduates { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Perfomance> Perfomance { get; set; }
        public virtual DbSet<Specialty> Specialty { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Transfer> Transfer { get; set; }
        public virtual DbSet<University> University { get; set; }
    }
}
