//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSU.University.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        public int Id { get; set; }
        public Nullable<int> IdStudent { get; set; }
        public int IdOldUniversity { get; set; }
        public Nullable<int> IdNewUniversity { get; set; }
        public int IdOldFaculty { get; set; }
        public int IdOldGroup { get; set; }
        public Nullable<int> IdNewGroup { get; set; }
        public System.DateTime DateTransfer { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
